<a href="https://colab.research.google.com/github/puja-hansitha/nasscomlab1/blob/main/Practice_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔢 Introduction to NumPy

### For B.Tech II Year CSE Students | AI/ML & Programming Practical

Full explanations, ML motivation, and function tables are in the companion file:
**`NumPy_Definitions.md`** — read the matching section there before each Demo.

**How to use this notebook:**
1. Read the matching section in the definitions file first.
2. Run each **Demo** cell.
3. Complete the **Practice** cell (replace every `# TODO`).

**Topics:** Why NumPy → Creating Arrays → Indexing & Reshaping → Aggregate Functions →
Vectorized Ops & Broadcasting → Dot Product & Matrix Multiplication

---

In [1]:
# ------------------------------------------------------------- #
# 🔹 0. SETUP
# ------------------------------------------------------------- #
import numpy as np

## 1️⃣ Why NumPy Arrays?
*(see NumPy_Definitions.md → Why NumPy Arrays for the full explanation)*

In [2]:
# ------------------------------------------------------------- #
# 🔹 1. WHY NUMPY — DEMO
# ------------------------------------------------------------- #

python_list = list(range(1_000_000))
numpy_array = np.arange(1_000_000)

import time

start = time.time()
doubled_list = [x * 2 for x in python_list]
list_time = time.time() - start

start = time.time()
doubled_array = numpy_array * 2
array_time = time.time() - start

print(f"Python list loop: {list_time:.4f} sec")
print(f"NumPy vectorized: {array_time:.4f} sec")
print(f"NumPy was ~{list_time / array_time:.0f}x faster")

Python list loop: 0.0277 sec
NumPy vectorized: 0.0019 sec
NumPy was ~15x faster


### 📝 Practice — Why NumPy

In [4]:
# ------------------------------------------------------------- #
# 🔹 1. WHY NUMPY — PRACTICE
# ------------------------------------------------------------- #

prices = [199, 249, 99, 349, 149]   # plain Python list, prices in Rs.

# TODO 1: Convert `prices` into a NumPy array called `prices_arr`
prices_arr = np.array(prices)

# TODO 2: Apply an 18% GST increase to EVERY price in ONE vectorized line
#         (no loop!) and store the result in `prices_with_gst`
prices_with_gst = prices_arr * 1.18

print("Prices with GST:", prices_with_gst)

Prices with GST: [234.82 293.82 116.82 411.82 175.82]


## 2️⃣ Creating & Inspecting Arrays
*(see NumPy_Definitions.md → Creating & Inspecting Arrays for the function table)*

In [10]:
# ------------------------------------------------------------- #
# 🔹 2. CREATING & INSPECTING ARRAYS — DEMO
# ------------------------------------------------------------- #

marks = np.array([56, 78, 90, 45, 88])
print("From a list:", marks)

zeros = np.zeros((2, 3))
print("Zeros placeholder:\n", zeros)

ones = np.ones((3,))
print("Ones placeholder:", ones)

epochs = np.arange(0, 10, 2)
print("arange (step 2):", epochs)

smooth_x = np.linspace(0, 1, 5)
print("linspace (5 points 0 to 1):", smooth_x)

np.random.seed(42)
weights = np.random.rand(2, 3)
print("Random weights:\n", weights)

print("Shape:", marks.shape)
print("Dtype:", marks.dtype)
print("Ndim:", weights.ndim)

From a list: [56 78 90 45 88]
Zeros placeholder:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones placeholder: [1. 1. 1.]
arange (step 2): [0 2 4 6 8]
linspace (5 points 0 to 1): [0.   0.25 0.5  0.75 1.  ]
Random weights:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
Shape: (5,)
Dtype: int64
Ndim: 2


### 📝 Practice — Creating & Inspecting Arrays

In [5]:
# ------------------------------------------------------------- #
# 🔹 2. CREATING & INSPECTING ARRAYS — PRACTICE
# ------------------------------------------------------------- #

# TODO 1: Create a 1D array `attendance` from the list [80, 92, 76, 88, 95]
attendance = np.array([80, 92, 76, 88, 95])

# TODO 2: Create a (3, 3) array of zeros called `blank_grid`
blank_grid = np.zeros((3, 3))

# TODO 3: Create an array `weeks` of numbers 1 to 12 using arange
weeks = np.arange(1, 13)

# TODO 4: Print the .shape and .dtype of `attendance`
print("Shape of attendance:", attendance.shape)
print("Dtype of attendance:", attendance.dtype)

print("Attendance:", attendance)
print("Blank grid:\n", blank_grid)
print("Weeks:", weeks)

Shape of attendance: (5,)
Dtype of attendance: int64
Attendance: [80 92 76 88 95]
Blank grid:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Weeks: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 3️⃣ Indexing, Slicing & Reshaping
*(see NumPy_Definitions.md → Indexing, Slicing & Reshaping for the function table)*

In [11]:
# ------------------------------------------------------------- #
# 🔹 3. INDEXING, SLICING & RESHAPING — DEMO
# ------------------------------------------------------------- #

# rows = students, columns = subject marks (Python, Maths, AI)
scores = np.array([
    [88, 76, 91],
    [92, 81, 85],
    [67, 90, 72],
    [45, 60, 58],
])

print("First student's marks:", scores[0])
print("Second student's Maths mark:", scores[1, 1])
print("Everyone's AI marks (column 2):", scores[:, 2])
print("First two students:\n", scores[:2])

high_python_scores = scores[scores[:, 0] > 80]
print("Students who scored >80 in Python:\n", high_python_scores)

flattened = scores.flatten()
print("Flattened:", flattened)

reshaped = flattened.reshape(2, 6)
print("Reshaped to (2, 6):\n", reshaped)

First student's marks: [88 76 91]
Second student's Maths mark: 81
Everyone's AI marks (column 2): [91 85 72 58]
First two students:
 [[88 76 91]
 [92 81 85]]
Students who scored >80 in Python:
 [[88 76 91]
 [92 81 85]]
Flattened: [88 76 91 92 81 85 67 90 72 45 60 58]
Reshaped to (2, 6):
 [[88 76 91 92 81 85]
 [67 90 72 45 60 58]]


### 📝 Practice — Indexing, Slicing & Reshaping

In [6]:
# ------------------------------------------------------------- #
# 🔹 3. INDEXING, SLICING & RESHAPING — PRACTICE
# ------------------------------------------------------------- #

grid = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
])

# TODO 1: Print the LAST row of `grid`
print("Last row of grid:", grid[-1])

# TODO 2: Print the SECOND column of `grid` (all rows)
print("Second column of grid:", grid[:, 1])

# TODO 3: Print only the values in `grid` that are greater than 60 (boolean indexing)
print("Values greater than 60:", grid[grid > 60])

# TODO 4: Reshape `grid` into shape (2, 6) and store it as `grid_reshaped`
grid_reshaped = grid.reshape(2, 6)

print("Reshaped grid:\n", grid_reshaped)

Last row of grid: [ 90 100 110 120]
Second column of grid: [ 20  60 100]
Values greater than 60: [ 70  80  90 100 110 120]
Reshaped grid:
 [[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]


## 4️⃣ Aggregate Functions
*(see NumPy_Definitions.md → Aggregate Functions for the axis explanation and function table)*

In [12]:
# ------------------------------------------------------------- #
# 🔹 4. AGGREGATE FUNCTIONS — DEMO
# ------------------------------------------------------------- #

data = np.array([[5, 8, 9], [2, 4, 6]])
print("Original Data:\n", data)

print("Sum of all elements:", np.sum(data))
print("Sum per column (axis=0):", np.sum(data, axis=0))
print("Sum per row (axis=1):", np.sum(data, axis=1))

print("Mean per column (axis=0):", np.mean(data, axis=0))
print("Max value overall:", np.max(data))
print("Std deviation per column (axis=0):", np.std(data, axis=0))

print("Index of max value per row (argmax):", np.argmax(data, axis=1))

Original Data:
 [[5 8 9]
 [2 4 6]]
Sum of all elements: 34
Sum per column (axis=0): [ 7 12 15]
Sum per row (axis=1): [22 12]
Mean per column (axis=0): [3.5 6.  7.5]
Max value overall: 9
Std deviation per column (axis=0): [1.5 2.  1.5]
Index of max value per row (argmax): [2 2]


### 📝 Practice — Aggregate Functions

In [13]:
# ------------------------------------------------------------- #
# 🔹 4. AGGREGATE FUNCTIONS — PRACTICE
# ------------------------------------------------------------- #

# rows = students, columns = marks in (Python, Maths, AI)
scores = np.array([
    [88, 76, 91],
    [92, 81, 85],
    [67, 90, 72],
    [45, 60, 58],
])

# TODO 1: Find the average mark PER SUBJECT (column-wise mean)
avg_per_subject = np.mean(scores, axis=0)

# TODO 2: Find the total mark PER STUDENT (row-wise sum)
total_per_student = np.sum(scores, axis=1)

# TODO 3: Find the highest mark in the ENTIRE array
highest_mark_overall = np.max(scores)
print("Highest mark overall:", highest_mark_overall)

# TODO 4: For each student, find which SUBJECT (column index) they scored highest in
#         (hint: np.argmax with the correct axis)
highest_subject_index_per_student = np.argmax(scores, axis=1)
print("Highest subject index per student:", highest_subject_index_per_student)

print("Average per subject:", avg_per_subject)
print("Total per student:", total_per_student)

Highest mark overall: 92
Highest subject index per student: [2 0 1 1]
Average per subject: [73.   76.75 76.5 ]
Total per student: [255 258 229 163]


## 5️⃣ Vectorized Operations & Broadcasting
*(see NumPy_Definitions.md → Vectorized Operations & Broadcasting for the full explanation)*

In [14]:
# ------------------------------------------------------------- #
# 🔹 5. VECTORIZED OPS & BROADCASTING — DEMO
# ------------------------------------------------------------- #

pixels = np.array([0, 64, 128, 192, 255])
normalized = pixels / 255
print("Normalized pixels (0-1 range):", normalized)

batch = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
])
bias = np.array([10, 20, 30])   # one bias per column

print("Batch + bias (broadcasting):\n", batch + bias)

passed = batch[:, 0] > 3
print("First column > 3 (boolean mask):", passed)

Normalized pixels (0-1 range): [0.         0.25098039 0.50196078 0.75294118 1.        ]
Batch + bias (broadcasting):
 [[11. 22. 33.]
 [14. 25. 36.]
 [17. 28. 39.]]
First column > 3 (boolean mask): [False  True  True]


### 📝 Practice — Vectorized Ops & Broadcasting

In [15]:
# ------------------------------------------------------------- #
# 🔹 5. VECTORIZED OPS & BROADCASTING — PRACTICE
# ------------------------------------------------------------- #

temperatures_celsius = np.array([20, 25, 30, 15, 40])

# TODO 1: Convert ALL temperatures to Fahrenheit in ONE vectorized line
#         formula: F = C * 9/5 + 32
temperatures_fahrenheit = temperatures_celsius * 9/5 + 32

features = np.array([
    [1.0, 200.0],
    [2.0, 400.0],
    [3.0, 600.0],
])
offset = np.array([0.5, 100.0])   # one offset per column

# TODO 2: Add `offset` to every row of `features` using broadcasting
adjusted_features = features + offset

# TODO 3: Create a boolean mask of which temperatures are ABOVE 25°C (no loop)
above_25_mask = temperatures_celsius > 25

print("Fahrenheit:", temperatures_fahrenheit)
print("Adjusted features:\n", adjusted_features)
print("Above 25C mask:", above_25_mask)

Fahrenheit: [ 68.  77.  86.  59. 104.]
Adjusted features:
 [[  1.5 300. ]
 [  2.5 500. ]
 [  3.5 700. ]]
Above 25C mask: [False False  True False  True]


## 6️⃣ Dot Product & Matrix Multiplication
*(see NumPy_Definitions.md → Dot Product & Matrix Multiplication — the key ML connection)*

In [16]:
# ------------------------------------------------------------- #
# 🔹 6. DOT PRODUCT & MATRIX MULTIPLICATION — DEMO
# ------------------------------------------------------------- #

# A single neuron: 3 inputs, 3 matching weights, 1 bias
inputs = np.array([0.5, 0.8, 0.2])
weights = np.array([0.4, 0.7, 0.1])
bias = 0.1

neuron_output = np.dot(inputs, weights) + bias
print("Single neuron output:", neuron_output)

# A layer: 4 samples (rows) x 3 features, going through 3 neurons (3 weight columns)
X = np.array([
    [0.5, 0.8, 0.2],
    [0.1, 0.9, 0.6],
    [0.7, 0.3, 0.4],
    [0.9, 0.1, 0.8],
])
W = np.array([
    [0.4, 0.2, 0.9],
    [0.7, 0.5, 0.1],
    [0.1, 0.8, 0.3],
])

print("X shape:", X.shape, "| W shape:", W.shape)
layer_output = X @ W
print("Layer output shape:", layer_output.shape)
print("Layer output:\n", layer_output)

print("Transposed W shape:", W.T.shape)

Single neuron output: 0.88
X shape: (4, 3) | W shape: (3, 3)
Layer output shape: (4, 3)
Layer output:
 [[0.78 0.66 0.59]
 [0.73 0.95 0.36]
 [0.53 0.61 0.78]
 [0.51 0.87 1.06]]
Transposed W shape: (3, 3)


### 📝 Practice — Dot Product & Matrix Multiplication

In [17]:
# ------------------------------------------------------------- #
# 🔹 6. DOT PRODUCT & MATRIX MULTIPLICATION — PRACTICE
# ------------------------------------------------------------- #

# Predicting a house price from 3 features: [size_in_100sqft, bedrooms, age_years]
house_features = np.array([12, 3, 5])
learned_weights = np.array([15.0, 8.0, -0.5])
learned_bias = 10.0

# TODO 1: Compute the predicted price using a dot product of features and weights, plus bias
single_prediction = np.dot(house_features, learned_weights) + learned_bias

batch_houses = np.array([
    [12, 3, 5],
    [8, 2, 10],
    [20, 4, 2],
])

# TODO 2: Compute predictions for ALL houses in `batch_houses` at once using matrix
#         multiplication with `learned_weights` (hint: shape (3,3) needs matching --
#         check .shape before you multiply!)
batch_predictions = batch_houses @ learned_weights + learned_bias


print("Single prediction:", single_prediction)
print("Batch predictions:", batch_predictions)

Single prediction: 211.5
Batch predictions: [211.5 141.  341. ]


---
## ✅ End of Notebook

You've covered the NumPy foundation every ML library builds on: **why arrays beat lists,
creating/inspecting arrays, indexing & reshaping, aggregation, vectorization & broadcasting,
and dot products & matrix multiplication.**

See `NumPy_Definitions.md` for full explanations and the ML connections behind each section.